spring:
  datasource:
    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

app:
  default-page-size: 5
  max-page-size: 50
  cors:
    allowed-origins: "*"